name: server_bff
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  http: ^0.13.6
  args: ^2.4.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
